language: php
sudo: false
dist: trusty

matrix:
    include:
        - php: 7.0
        - php: 7.1
          env: DEPENDENCIES=beta

before_install:
    - if [ "$DEPENDENCIES" = "beta" ]; then composer config minimum-stability beta; fi;
    - echo "" > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini

before_script:
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    - composer install --no-interaction --prefer-dist

cache:
    directories:
        - bin
        - vendor
        - ~/.composer/cache/files

script:
    - bin/coke
    - bin/phpspec run -f dot -n
