dist: bionic

language: php

cache:
    directories:
        - vendor
        - ~/.composer/cache/files

env:
    global:
        - COMPOSER_MEMORY_LIMIT=-1

matrix:
    fast_finish: true
    include:
        # Minimum supported dependencies with the latest and oldest PHP version
        - php: 7.3
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="max[self]=0"
        - php: 7.4
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="max[self]=0"

        # Test the latest stable release
        - php: 7.3
        - php: 7.4

        # Test specific Symfony versions
        - php: 7.4
          env: SYMFONY_REQUIRE="4.4.10" # LTS
        - php: 7.4
          env: SYMFONY_REQUIRE="4.*" # Last 4.x version
        - php: 7.4
          env: SYMFONY_REQUIRE="5.*" # Last 5.x version

        # Latest commit to master
        - php: 7.4
          env: STABILITY="dev"

    allow_failures:
        # Dev-master is allowed to fail.
        - env: STABILITY="dev"
        - env: SYMFONY_REQUIRE="5.*"

before_install:
    - phpenv config-rm xdebug.ini
    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
    - composer global require --no-progress --no-scripts --no-plugins symfony/flex dev-master ${DEPENDENCIES}

before_script:
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;

install:
    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
    - bin/php-cs-fixer fix --verbose --diff --dry-run src/
    - bin/phpspec run -f dot -n
