parameters:
    yproximite.influx_db_preset.event_listener.extension.exception.class: Yproximite\Bundle\InfluxDbPresetBundle\EventListener\Extension\ExceptionListener

services:
    yproximite.influx_db_preset.event_listener.extension.exception:
        parent: yproximite.influx_db_preset.event_listener.extension.abstract
        class: "%yproximite.influx_db_preset.event_listener.extension.exception.class%"
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
