parameters:
    yproximite.influx_db_preset.event_listener.extension.memory.class: Yproximite\Bundle\InfluxDbPresetBundle\EventListener\Extension\MemoryListener

services:
    yproximite.influx_db_preset.event_listener.extension.memory:
        parent: yproximite.influx_db_preset.event_listener.extension.abstract
        class: "%yproximite.influx_db_preset.event_listener.extension.memory.class%"
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate, priority: 1 }
